### ISSUE TITLE
Sort by vote count

### ISSUE THREAD

**Issue by ztalk112** [crazyhitty/Capstone-Project#24]
Like your app, but would be much more useful IMO if it sorted the day's PH listings by vote count (highest to lowest) by default.

Cheers.

Android 6.0.1, Nexus 5

**Comment by crazyhitty** [comment]
Thanks for contributing @ztalk112. I have added this to my list, meanwhile, it would be great if you could give the application feedback/rating on google play: https://play.google.com/store/apps/details?id=com.crazyhitty.chdev.ks.predator

**Comment by crazyhitty** [comment]
@ztalk112 This feature is now available in the latest version 👍

**Comment by ztalk112** [comment]
Cool bananas!

Thx for listening.

Gary
