### ISSUE TITLE
Sort by upvote

### ISSUE THREAD

**Issue by ztalk112** [crazyhitty/Capstone-Project#40]
Latest update intended to add post sorting by upvote has no effect on Nexus 7 tablet (2013) or Nexus 5 phone.

Default sort order appears to be the same and I don't see any sort options in settings.

After updating on both devices, I removed/reinstalled with the same result.

As an aside, it would be nice to be able to see the vote count for each listing in the summary view as shown in this screenshot from Feline for Product Hunt:

![feline for phunt](https://user-images.githubusercontent.com/30450078/31048869-84657f74-a683-11e7-85a1-dec4022b5453.png)

**Comment by crazyhitty** [comment]
@ztalk112 Sorting order can be changed in dashboard only. Please check this video on how to sort posts.

https://drive.google.com/open?id=0B0dm5g3rW9BzU1BjUWVYX3JxUjQ

Also, regarding your second request, I am also thinking the same. I might provide an option in future to switch between normal and detailed mode, where detailed mode will contain more information.

**Comment by ztalk112** [comment]
Sorry, my mistake . . . I only looked in the settings!

Works as intended now. Thanks for the prompt followup and video.
